### ISSUE TITLE
Allow multiple funders to be listed on a hub homepage

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/default-hub-homepage#16]
### Context

We have a field where we can provide the name and link of a funder that provides financial support for a hub. However, some communities may have funding from multiple sources that they may wish to acknowledge, e.g.:

- https://github.com/2i2c-org/infrastructure/issues/1702

### Proposal

I propose we move from the current config that only allows us to list a single funder, to a config that would allow us to list multiple

Current config example:

```
funded_by:
  name: Funder 1
  url: https://www.funder1.org/
```

Proposed config example (make `funded_by` an array type):

```
funded_by:
  - name: Funder 1
    url: https://www.funder1.org/
  - name: Funder 2
    url: https://funder2.com
```

### Updates and actions

- There will need to be some exploration on how to best *display* multiple funders in terms of the HTML
